<a href="javascript:void(0);" class="load-kitties top btn btn-primary btn-large">Load more kitties</a>

<div id="columns">
    <?php foreach($kitties as $kitty): ?>
        <div class="pin">
           <img style='<?php echo "width: {$kitty->getWidth()}px; height: {$kitty->getHeight()}px" ?>' src="<?php echo $kitty->getUrl() ?>">
           <a href="javascript:void(0);"
              data-width="<?php echo $kitty->getWidth()?>"
              data-height="<?php echo $kitty->getHeight()?>"
              class="like-kitty btn">Like it</a>
        </div>
    <?php endforeach ?>
</div>

<a href="javascript:void(0)" class="load-kitties bottom btn btn-primary btn-large">Load more kitties</a>
